/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebsiteMaintenanceSupportRouteImport } from './routes/services/website-maintenance-support'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services/website-development'
import { Route as ServicesUiUxDesignRouteImport } from './routes/services/ui-ux-design'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services/software-development'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services/mobile-app-development'
import { Route as ServicesECommerceSolutionsRouteImport } from './routes/services/e-commerce-solutions'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services/digital-marketing'
import { Route as ServicesCloudSolutionsRouteImport } from './routes/services/cloud-solutions'
import { Route as ServicesBrandingRouteImport } from './routes/services/branding'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteMaintenanceSupportRoute =
  ServicesWebsiteMaintenanceSupportRouteImport.update({
    id: '/services/website-maintenance-support',
    path: '/services/website-maintenance-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/services/website-development',
    path: '/services/website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUiUxDesignRoute = ServicesUiUxDesignRouteImport.update({
  id: '/services/ui-ux-design',
  path: '/services/ui-ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesECommerceSolutionsRoute =
  ServicesECommerceSolutionsRouteImport.update({
    id: '/services/e-commerce-solutions',
    path: '/services/e-commerce-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/services/digital-marketing',
    path: '/services/digital-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCloudSolutionsRoute = ServicesCloudSolutionsRouteImport.update({
  id: '/services/cloud-solutions',
  path: '/services/cloud-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/services/branding',
  path: '/services/branding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/e-commerce-solutions': typeof ServicesECommerceSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/website-maintenance-support': typeof ServicesWebsiteMaintenanceSupportRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/e-commerce-solutions': typeof ServicesECommerceSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/website-maintenance-support': typeof ServicesWebsiteMaintenanceSupportRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/e-commerce-solutions': typeof ServicesECommerceSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/website-maintenance-support': typeof ServicesWebsiteMaintenanceSupportRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/services/branding'
    | '/services/cloud-solutions'
    | '/services/digital-marketing'
    | '/services/e-commerce-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/ui-ux-design'
    | '/services/website-development'
    | '/services/website-maintenance-support'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/services/branding'
    | '/services/cloud-solutions'
    | '/services/digital-marketing'
    | '/services/e-commerce-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/ui-ux-design'
    | '/services/website-development'
    | '/services/website-maintenance-support'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/services/branding'
    | '/services/cloud-solutions'
    | '/services/digital-marketing'
    | '/services/e-commerce-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/ui-ux-design'
    | '/services/website-development'
    | '/services/website-maintenance-support'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesCloudSolutionsRoute: typeof ServicesCloudSolutionsRoute
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesECommerceSolutionsRoute: typeof ServicesECommerceSolutionsRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesUiUxDesignRoute: typeof ServicesUiUxDesignRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesWebsiteMaintenanceSupportRoute: typeof ServicesWebsiteMaintenanceSupportRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-maintenance-support': {
      id: '/services/website-maintenance-support'
      path: '/services/website-maintenance-support'
      fullPath: '/services/website-maintenance-support'
      preLoaderRoute: typeof ServicesWebsiteMaintenanceSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/services/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ui-ux-design': {
      id: '/services/ui-ux-design'
      path: '/services/ui-ux-design'
      fullPath: '/services/ui-ux-design'
      preLoaderRoute: typeof ServicesUiUxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/e-commerce-solutions': {
      id: '/services/e-commerce-solutions'
      path: '/services/e-commerce-solutions'
      fullPath: '/services/e-commerce-solutions'
      preLoaderRoute: typeof ServicesECommerceSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/services/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-solutions': {
      id: '/services/cloud-solutions'
      path: '/services/cloud-solutions'
      fullPath: '/services/cloud-solutions'
      preLoaderRoute: typeof ServicesCloudSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/services/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesCloudSolutionsRoute: ServicesCloudSolutionsRoute,
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesECommerceSolutionsRoute: ServicesECommerceSolutionsRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesUiUxDesignRoute: ServicesUiUxDesignRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesWebsiteMaintenanceSupportRoute:
    ServicesWebsiteMaintenanceSupportRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
